In [449]:
import pandas as pd

In [450]:
df_listings = pd.read_csv('D:/Data analyst/Python_Data_Project/airbnb/listings.csv')

df_cal = pd.read_csv('D:/Data analyst/Python_Data_Project/airbnb/calendar.csv')

In [451]:
# Remove the dollar sign and convert the column to a numeric type
df_listings['price'] = df_listings['price'].replace('[\$,]', '', regex=True).astype(float)

# Drop any NA values
df_listings.dropna(subset=['price'])

df_listings.head(3)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,241032,https://www.airbnb.com/rooms/241032,20160104002432,2016-01-04,Stylish Queen Anne Apartment,NaN,Make your self at home in this charming one-be...,Make your self at home in this charming one-be...,none,NaN,NaN,NaN,NaN,NaN,https://a1.muscache.com/ac/pictures/67560560/c...,NaN,956883,https://www.airbnb.com/users/show/956883,Maija,2011-08-11,"Seattle, Washington, United States","I am an artist, interior designer, and run a s...",within a few hours,96%,100%,f,https://a0.muscache.com/ac/users/956883/profil...,https://a0.muscache.com/ac/users/956883/profil...,Queen Anne,3.0,3.0,"['email', 'phone', 'reviews', 'kba']",t,t,"Gilman Dr W, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.636289,-122.371025,t,Apartment,Entire home/apt,4,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",NaN,85.0,NaN,NaN,NaN,NaN,2,$5.00,1,365,4 weeks ago,t,14,41,71,346,2016-01-04,207,2011-11-01,2016-01-02,95.0,10.0,10.0,10.0,10.0,9.0,10.0,f,NaN,WASHINGTON,f,moderate,f,f,2,4.07
1,953595,https://www.airbnb.com/rooms/953595,20160104002432,2016-01-04,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...",What's up with the free pillows? Our home was...,"Convenient bus stops are just down the block, ...",https://a0.muscache.com/ac/pictures/14409893/f...,https://a0.muscache.com/im/pictures/14409893/f...,https://a0.muscache.com/ac/pictures/14409893/f...,https://a0.muscache.com/ac/pictures/14409893/f...,5177328,https://www.airbnb.com/users/show/5177328,Andrea,2013-02-21,"Seattle, Washington, United States",Living east coast/left coast/overseas. Time i...,within an hour,98%,100%,t,https://a0.muscache.com/ac/users/5177328/profi...,https://a0.muscache.com/ac/users/5177328/profi...,Queen Anne,6.0,6.0,"['email', 'phone', 'facebook', 'linkedin', 're...",t,t,"7th Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.639123,-122.365666,t,Apartment,Entire home/apt,4,1.0,1.0,1.0,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",NaN,150.0,"$1,000.00","$3,000.00",$100.00,$40.00,1,$0.00,2,90,today,t,13,13,16,291,2016-01-04,43,2013-08-19,2015-12-29,96.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,WASHINGTON,f,strict,t,t,6,1.48
2,3308979,https://www.airbnb.com/rooms/3308979,20160104002432,2016-01-04,New Modern House-Amazing water view,New modern house built in 2013. Spectacular s...,"Our house is modern, light and fresh with a wa...",New modern house built in 2013. Spectacular s...,none,Upper Queen Anne is a charming neighborhood fu...,Our house is located just 5 short blocks to To...,A bus stop is just 2 blocks away. Easy bus a...,NaN,NaN,https://a2.muscache.com/ac/pictures/b4324e0f-a...,NaN,16708587,https://www.airbnb.com/users/show/16708587,Jill,2014-06-12,"Seattle, Washington, United States",i love living in Seattle. i grew up in the mi...,within a few hours,67%,100%,f,https://a1.muscache.com/ac/users/16708587/prof...,https://a1.muscache.com/ac/users/16708587/prof...,Queen Anne,2.0,2.0,"['email', 'phone', 'google', 'reviews', 'jumio']",t,t,"West Lee Street, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.629724,-122.369483,t,House,Entire home/apt,11,4.5,5.0,7.0,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",NaN,975.0,NaN,NaN,"$1,000.00",$300.00,10,$25.00,4,30,5 weeks ago,t,1,6,17,220,2016-01-04,20,2014-07-30,2015-09-03,97.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,WASHINGTON,f,strict,f,f,2,1.15

In [452]:
# Remove the dollar sign and convert the column to a numeric type
df_cal['price'] = df_cal['price'].replace('[\$,]', '', regex=True).astype(float)

# Drop any NA values
df_cal.dropna(subset=['price','date'])

df_cal.head()

   listing_id        date available  price
0      241032  2016-01-04         t   85.0
1      241032  2016-01-05         t   85.0
2      241032  2016-01-06         f    NaN
3      241032  2016-01-07         f    NaN
4      241032  2016-01-08         f    NaN

In [453]:
# Remove unwanted columns from listings df
df_listings = df_listings.drop(columns=['listing_url', 'summary','space','description','scrape_id', 'last_scraped','host_is_superhost', 'state'	,'name',	'summary',	'space',	'description',	'experiences_offered',	'neighborhood_overview',	'notes',	'transit',	'thumbnail_url'	,'medium_url',	'picture_url',	'xl_picture_url',	'host_url',	'host_name',	'host_location',	'host_about',	'host_response_time',	'host_response_rate',	'host_acceptance_rate',	'host_thumbnail_url',	'host_picture_url',	'host_neighbourhood',	'host_listings_count',	'host_total_listings_count',	'host_verifications',	'host_has_profile_pic',	'host_identity_verified',	'street',	'neighbourhood',	'neighbourhood_cleansed',	'neighbourhood_group_cleansed',	'market',	'smart_location',	'country_code',	'country',	'is_location_exact',	'room_type',	'bathrooms',	'bed_type',	'amenities',	'square_feet',	'weekly_price',	'monthly_price',	'security_deposit',	'cleaning_fee',	'guests_included',	'extra_people',	'minimum_nights',	'maximum_nights',	'calendar_updated',	'has_availability',	'availability_30',	'availability_60',	'availability_90',	'availability_365',	'calendar_last_scraped',	'number_of_reviews',	'first_review',	'last_review',	'review_scores_rating',	'review_scores_accuracy',	'review_scores_cleanliness',	'review_scores_checkin',	'review_scores_communication',	'review_scores_location',	'review_scores_value',	'requires_license',	'license',	'jurisdiction_names',	'instant_bookable',	'cancellation_policy',	'require_guest_profile_picture',	'require_guest_phone_verification',	'calculated_host_listings_count',	'reviews_per_month'])

# Set display option to show all columns
pd.set_option('display.max_columns', None)

# Display the first few rows to verify the change
df_listings.head()

,id,host_id,host_since,city,zipcode,latitude,longitude,property_type,accommodates,bedrooms,beds,price
0,241032,956883,2011-08-11,Seattle,98119,47.636289,-122.371025,Apartment,4,1.0,1.0,85.0
1,953595,5177328,2013-02-21,Seattle,98119,47.639123,-122.365666,Apartment,4,1.0,1.0,150.0
2,3308979,16708587,2014-06-12,Seattle,98119,47.629724,-122.369483,House,11,5.0,7.0,975.0
3,7421966,9851441,2013-11-06,Seattle,98119,47.638473,-122.369279,Apartment,3,0.0,2.0,100.0
4,278830,1452570,2011-11-29,Seattle,98119,47.632918,-122.372471,House,6,3.0,3.0,450.0

In [454]:
df_listings.to_csv('airbnb_listings.csv')
df_cal.to_csv('airbnb_calendar.csv')